@startuml
'https://plantuml.com/state-diagram

scale 700 width
[*] --> Initial

Initial --> UpstreamPolled::Successful
Initial --> UpstreamPolled::Error

UpstreamPolled::Successful --> Finish
UpstreamPolled::Error --> Finish

Finish --> [*]

@enduml