[package]
name = "hitbox-fn"
version = "0.1.0"
description = "Function memoization for hitbox caching framework"
keywords = ["cache", "memoization", "async", "function"]
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
default = []
derive = ["hitbox-derive"]
rkyv_format = ["hitbox/rkyv_format", "hitbox-core/rkyv_format"]

[dependencies]
hitbox = { path = "../hitbox" }
hitbox-core = { path = "../hitbox-core" }
hitbox-derive = { path = "../hitbox-derive", optional = true }

async-trait = { workspace = true }
pin-project = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }
serde = { workspace = true }
hitbox-moka = { path = "../hitbox-moka" }
hitbox-derive = { path = "../hitbox-derive" }
