//! Compile-time typed protobuf field predicate.
//!
//! [`TypedProtoField`] decodes to a concrete `prost::Message` type and applies
//! a user-provided closure for the cache decision.
//!
//! This is the compile-time counterpart to [`ProtoField`](super::field::ProtoField).
//! It avoids the overhead of runtime reflection by decoding directly to a
//! generated prost type.
//!
//! # Examples
//!
//! ```no_run
//! use hitbox_proto::predicates::typed::TypedProtoField;
//! use hitbox_proto::decode::identity_bytes;
//!
//! // Assuming `GetUserRequest` is generated by prost-build:
//! // let predicate = TypedProtoField::<_, _, GetUserRequest, _>::new(
//! //     |msg: &GetUserRequest| msg.user_id > 0,
//! //     identity_bytes,
//! // );
//! ```

use std::marker::PhantomData;

use async_trait::async_trait;
use hitbox::Neutral;
use hitbox::predicate::{Predicate, PredicateResult};
use hyper::body::Body as HttpBody;
use tracing::warn;

use crate::CacheableSubject;
use crate::decode::BytesExtractor;

/// A predicate that decodes the body to a concrete protobuf type and applies a closure.
///
/// # Type Parameters
///
/// * `P` - Inner predicate in the chain
/// * `M` - The concrete protobuf message type (must implement `prost::Message + Default`)
/// * `F` - Closure `Fn(&M) -> bool` that determines cacheability
#[derive(Debug)]
pub struct TypedProtoField<P, M, F> {
    check_fn: F,
    bytes_extractor: BytesExtractor,
    inner: P,
    _marker: PhantomData<M>,
}

impl<S, M, F> TypedProtoField<Neutral<S>, M, F>
where
    M: prost::Message + Default,
    F: Fn(&M) -> bool,
{
    /// Creates a new typed predicate that starts a predicate chain.
    ///
    /// # Arguments
    ///
    /// * `check_fn` - Closure that receives the decoded message and returns `true` for cacheable
    /// * `bytes_extractor` - Pre-processing function (e.g., gRPC frame stripping)
    pub fn new(check_fn: F, bytes_extractor: BytesExtractor) -> Self {
        TypedProtoField {
            check_fn,
            bytes_extractor,
            inner: Neutral::new(),
            _marker: PhantomData,
        }
    }
}

/// Extension trait for adding typed protobuf field matching to a predicate chain.
pub trait TypedProtoFieldPredicate: Sized {
    /// Adds a typed protobuf field check to this predicate chain.
    fn typed_proto_field<M, F>(
        self,
        check_fn: F,
        bytes_extractor: BytesExtractor,
    ) -> TypedProtoField<Self, M, F>
    where
        M: prost::Message + Default,
        F: Fn(&M) -> bool;
}

impl<P> TypedProtoFieldPredicate for P
where
    P: Predicate,
{
    fn typed_proto_field<M, F>(
        self,
        check_fn: F,
        bytes_extractor: BytesExtractor,
    ) -> TypedProtoField<Self, M, F>
    where
        M: prost::Message + Default,
        F: Fn(&M) -> bool,
    {
        TypedProtoField {
            check_fn,
            bytes_extractor,
            inner: self,
            _marker: PhantomData,
        }
    }
}

#[async_trait]
impl<P, M, F> Predicate for TypedProtoField<P, M, F>
where
    P: Predicate + Send + Sync,
    P::Subject: CacheableSubject + Send,
    <P::Subject as CacheableSubject>::Body: Send + Unpin + 'static,
    <P::Subject as CacheableSubject>::Parts: Send,
    <<P::Subject as CacheableSubject>::Body as HttpBody>::Error: Send,
    <<P::Subject as CacheableSubject>::Body as HttpBody>::Data: Send,
    M: prost::Message + Default + Send + Sync,
    F: Fn(&M) -> bool + Send + Sync,
{
    type Subject = P::Subject;

    async fn check(&self, subject: Self::Subject) -> PredicateResult<Self::Subject> {
        let inner_result = self.inner.check(subject).await;

        let (was_cacheable, subject) = match inner_result {
            PredicateResult::Cacheable(s) => (true, s),
            PredicateResult::NonCacheable(s) => (false, s),
        };

        let (parts, body) = subject.into_parts();

        let collected = match body.collect().await {
            Ok(collected) => collected,
            Err(error_body) => {
                warn!("TypedProtoField: failed to collect body");
                return PredicateResult::NonCacheable(P::Subject::from_parts(parts, error_body));
            }
        };

        let body_bytes = collected.data;
        let field_matches =
            match crate::decode::decode_typed::<M>(&body_bytes, self.bytes_extractor) {
                Ok(msg) => (self.check_fn)(&msg),
                Err(e) => {
                    warn!(%e, "TypedProtoField: failed to decode protobuf message");
                    false
                }
            };

        let body = hitbox_http::BufferedBody::Complete {
            data: Some(body_bytes),
            trailers: collected.trailers,
        };
        let subject = P::Subject::from_parts(parts, body);

        if was_cacheable && field_matches {
            PredicateResult::Cacheable(subject)
        } else {
            PredicateResult::NonCacheable(subject)
        }
    }
}

// Note: Integration tests for TypedProtoField require a concrete prost-generated type.
// These are tested in hitbox-grpc's integration tests with actual generated messages.
// Unit-level verification is done via ProtoField (same body inspection pattern).
