//! Protobuf decoding utilities.
//!
//! Provides both runtime (dynamic) and compile-time (typed) protobuf decoding,
//! along with the [`BytesExtractor`] type for pre-processing raw bytes before decoding.
//!
//! # BytesExtractor
//!
//! The [`BytesExtractor`] function type allows protocol-specific crates to strip
//! framing before decoding. For example, gRPC prepends a 5-byte frame header that
//! must be removed before protobuf decoding.
//!
//! - **gRPC**: strips the 5-byte frame header (`[compressed][4-byte length]`)
//! - **Twirp**: identity function (raw protobuf, no framing)

use prost_reflect::{DynamicMessage, MessageDescriptor};

/// Pre-processes raw body bytes before protobuf decoding.
///
/// Returns `Some(slice)` with the protobuf payload, or `None` if the input
/// is malformed (e.g., truncated gRPC frame).
///
/// # Built-in extractors
///
/// - [`identity_bytes`] — passes bytes through unchanged (for Twirp)
/// - gRPC frame stripping is provided by `hitbox-grpc`
pub type BytesExtractor = fn(&[u8]) -> Option<&[u8]>;

/// Identity bytes extractor that passes bytes through unchanged.
///
/// Use this for protocols like Twirp that don't add framing around the
/// protobuf payload.
pub fn identity_bytes(bytes: &[u8]) -> Option<&[u8]> {
    Some(bytes)
}

/// Errors that can occur during protobuf decoding.
#[derive(Debug)]
pub enum DecodeError {
    /// The [`BytesExtractor`] returned `None` (e.g., truncated frame).
    BytesExtraction,
    /// The protobuf decoding itself failed.
    Prost(prost::DecodeError),
}

impl std::fmt::Display for DecodeError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            DecodeError::BytesExtraction => write!(f, "bytes extraction failed (malformed frame?)"),
            DecodeError::Prost(e) => write!(f, "protobuf decode error: {e}"),
        }
    }
}

impl std::error::Error for DecodeError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            DecodeError::BytesExtraction => None,
            DecodeError::Prost(e) => Some(e),
        }
    }
}

/// Decodes raw bytes into a [`DynamicMessage`] using runtime reflection.
///
/// This is the runtime approach: you provide a [`MessageDescriptor`] (from
/// [`ProtoDescriptors`](crate::descriptor::ProtoDescriptors)) and the raw bytes
/// are decoded into a `DynamicMessage` whose fields can be inspected by name.
///
/// The `bytes_extractor` is applied first to strip any protocol framing.
///
/// # Errors
///
/// Returns [`DecodeError::BytesExtraction`] if the bytes extractor fails, or
/// [`DecodeError::Prost`] if the protobuf decoding fails.
pub fn decode_dynamic(
    descriptor: &MessageDescriptor,
    raw: &[u8],
    bytes_extractor: BytesExtractor,
) -> Result<DynamicMessage, DecodeError> {
    let payload = bytes_extractor(raw).ok_or(DecodeError::BytesExtraction)?;
    DynamicMessage::decode(descriptor.clone(), payload).map_err(DecodeError::Prost)
}

/// Decodes raw bytes into a concrete protobuf message type.
///
/// This is the compile-time approach: you provide a concrete type `M` that
/// implements [`prost::Message`] (typically generated by `prost-build`), and the
/// raw bytes are decoded directly into that type.
///
/// The `bytes_extractor` is applied first to strip any protocol framing.
///
/// # Errors
///
/// Returns [`DecodeError::BytesExtraction`] if the bytes extractor fails, or
/// [`DecodeError::Prost`] if the protobuf decoding fails.
pub fn decode_typed<M: prost::Message + Default>(
    raw: &[u8],
    bytes_extractor: BytesExtractor,
) -> Result<M, DecodeError> {
    let payload = bytes_extractor(raw).ok_or(DecodeError::BytesExtraction)?;
    M::decode(payload).map_err(DecodeError::Prost)
}

#[cfg(test)]
mod tests {
    use super::*;
    use prost::Message;
    use prost_reflect::Value;

    fn test_descriptors() -> crate::descriptor::ProtoDescriptors {
        crate::test_util::test_descriptors()
    }

    /// Encode a test GetUserRequest { user_id: 42, name: "alice" } using prost-reflect
    fn encode_test_message(descriptors: &crate::descriptor::ProtoDescriptors) -> Vec<u8> {
        let msg_desc = descriptors.get_message("test.GetUserRequest").unwrap();
        let mut msg = DynamicMessage::new(msg_desc);
        msg.set_field_by_name("user_id", Value::I64(42));
        msg.set_field_by_name("name", Value::String("alice".into()));

        let mut buf = Vec::new();
        msg.encode(&mut buf).unwrap();
        buf
    }

    #[test]
    fn decode_dynamic_identity() {
        let descriptors = test_descriptors();
        let encoded = encode_test_message(&descriptors);
        let msg_desc = descriptors.get_message("test.GetUserRequest").unwrap();

        let decoded = decode_dynamic(&msg_desc, &encoded, identity_bytes).unwrap();

        assert_eq!(
            decoded.get_field_by_name("user_id").unwrap().as_ref(),
            &Value::I64(42)
        );
        assert_eq!(
            decoded.get_field_by_name("name").unwrap().as_ref(),
            &Value::String("alice".into())
        );
    }

    #[test]
    fn decode_dynamic_with_extractor() {
        let descriptors = test_descriptors();
        let encoded = encode_test_message(&descriptors);

        // Simulate a simple frame: 2-byte prefix + payload
        let mut framed = vec![0x00, 0xFF];
        framed.extend_from_slice(&encoded);

        fn strip_prefix(bytes: &[u8]) -> Option<&[u8]> {
            if bytes.len() >= 2 {
                Some(&bytes[2..])
            } else {
                None
            }
        }

        let msg_desc = descriptors.get_message("test.GetUserRequest").unwrap();
        let decoded = decode_dynamic(&msg_desc, &framed, strip_prefix).unwrap();
        assert_eq!(
            decoded.get_field_by_name("user_id").unwrap().as_ref(),
            &Value::I64(42)
        );
    }

    #[test]
    fn decode_dynamic_bytes_extraction_failure() {
        let descriptors = test_descriptors();
        let msg_desc = descriptors.get_message("test.GetUserRequest").unwrap();

        fn always_fail(_: &[u8]) -> Option<&[u8]> {
            None
        }

        let result = decode_dynamic(&msg_desc, &[1, 2, 3], always_fail);
        assert!(matches!(result, Err(DecodeError::BytesExtraction)));
    }

    #[test]
    fn decode_dynamic_invalid_protobuf() {
        let descriptors = test_descriptors();
        let msg_desc = descriptors.get_message("test.GetUserRequest").unwrap();

        // Invalid protobuf bytes
        let result = decode_dynamic(&msg_desc, &[0xFF, 0xFF, 0xFF, 0xFF], identity_bytes);
        assert!(matches!(result, Err(DecodeError::Prost(_))));
    }

    #[test]
    fn decode_dynamic_default_values() {
        // Proto3 default: int64 = 0, string = ""
        let descriptors = test_descriptors();
        let msg_desc = descriptors.get_message("test.GetUserRequest").unwrap();

        // Empty message (all defaults)
        let decoded = decode_dynamic(&msg_desc, &[], identity_bytes).unwrap();
        assert_eq!(
            decoded.get_field_by_name("user_id").unwrap().as_ref(),
            &Value::I64(0)
        );
        assert_eq!(
            decoded.get_field_by_name("name").unwrap().as_ref(),
            &Value::String(String::new())
        );
    }
}
